import { useEffect, useMemo, useState } from 'react';
import type { Chat, CurrentChat, Interaction, Prompt, Settings, Usage, InputType, UsageType } from './types';
import { hashText, makeId, now } from './types';
import { ChatRepository, InteractionRepository, PromptRepository, PromptVersionRepository, SettingsRepository, UsageRepository, exportBackup, importBackup } from './services/repositories';
import { syncWithGoogle } from './services/cloudSync';
import './styles.css';

type View = 'home' | 'prompts' | 'chats' | 'activity' | 'settings';
const defaultSettings: Settings = { id: 'settings', autoRegisterChats: true, confirmBeforeSend: true, theme: 'system', locale: 'ar' };
const emptyPrompt = (): Prompt => ({ id: makeId('PRM'), title: '', description: '', content: '', category: 'عام', tags: [], favorite: false, archived: false, notes: '', createdAt: now(), updatedAt: now(), usageCount: 0, version: 1, variables: [] });

export default function App() {
  const [view, setView] = useState<View>('home'); const [prompts, setPrompts] = useState<Prompt[]>([]); const [chats, setChats] = useState<Chat[]>([]); const [usages, setUsages] = useState<Usage[]>([]); const [interactions, setInteractions] = useState<Interaction[]>([]); const [settings, setSettings] = useState<Settings>(defaultSettings); const [currentChat, setCurrentChat] = useState<CurrentChat | null>(null); const [query, setQuery] = useState(''); const [composer, setComposer] = useState(''); const [selectedPrompt, setSelectedPrompt] = useState<Prompt | null>(null); const [notice, setNotice] = useState(''); const [showPromptForm, setShowPromptForm] = useState(false); const [showChatForm, setShowChatForm] = useState(false); const [editingChat, setEditingChat] = useState<Chat | null>(null); const [chatTagFilter, setChatTagFilter] = useState(''); const [chatProviderFilter, setChatProviderFilter] = useState(''); const [chatFavoritesOnly, setChatFavoritesOnly] = useState(false);
  const refresh = async () => { setPrompts(await PromptRepository.list()); setChats(await ChatRepository.list()); setUsages(await UsageRepository.list()); setInteractions(await InteractionRepository.list()); const s = await SettingsRepository.get(); if (s) setSettings(s); };
  useEffect(() => { refresh(); detectCurrentChat(); const listener = (message: any) => { if (message.type === 'CHAT_CONTEXT_CHANGED') { setCurrentChat(message.chat); refresh(); } }; chrome.runtime.onMessage.addListener(listener); return () => chrome.runtime.onMessage.removeListener(listener); }, []);
  useEffect(() => { document.documentElement.dataset.theme = settings.theme; document.documentElement.dir = settings.locale === 'ar' ? 'rtl' : 'ltr'; }, [settings]);
  const detectCurrentChat = async () => { try { const tabs = await chrome.tabs.query({ active: true, lastFocusedWindow: true }); const tab = tabs[0]; if (!tab?.id) return; const result = await chrome.tabs.sendMessage(tab.id, { type: 'GET_CURRENT_CHAT' }); if (result) setCurrentChat(result); } catch { setCurrentChat(null); } };
  const filteredPrompts = useMemo(() => prompts.filter((p) => !p.archived && `${p.title} ${p.content} ${p.description} ${p.category} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [prompts, query]);
  const chatTags = useMemo(() => [...new Set(chats.flatMap((c) => c.tags))].sort((a, b) => a.localeCompare(b, 'ar')), [chats]); const chatProviders = useMemo(() => [...new Set(chats.map((c) => c.provider).filter(Boolean))].sort(), [chats]); const filteredChats = useMemo(() => chats.filter((c) => { const haystack = `${c.localName} ${c.originalTitle} ${c.url} ${c.provider} ${c.category} ${c.notes} ${c.tags.join(' ')}`.toLowerCase(); const matchesText = haystack.includes(query.toLowerCase()); const matchesTag = !chatTagFilter || c.tags.includes(chatTagFilter); const matchesProvider = !chatProviderFilter || c.provider === chatProviderFilter; const matchesFavorite = !chatFavoritesOnly || c.favorite; return matchesText && matchesTag && matchesProvider && matchesFavorite; }), [chats, query, chatTagFilter, chatProviderFilter, chatFavoritesOnly]);
  const notify = (text: string) => { setNotice(text); setTimeout(() => setNotice(''), 2600); };
  const ensureChat = async (): Promise<Chat | undefined> => { if (!currentChat) return undefined; const existing = chats.find((c) => c.identityKey === currentChat.identityKey); if (existing) { const updated = { ...existing, url: currentChat.url, originalTitle: currentChat.title, lastVisitedAt: now() }; await ChatRepository.put(updated); return updated; } const chat: Chat = { id: makeId('CHT'), localName: currentChat.title, originalTitle: currentChat.title, url: currentChat.url, provider: currentChat.provider, model: currentChat.model, category: 'عام', tags: [], favorite: false, notes: '', createdAt: now(), firstSeenAt: now(), lastVisitedAt: now(), promptUses: 0, interactions: 0, archived: false, identityKey: currentChat.identityKey }; await ChatRepository.put(chat); return chat; };
  const record = async (text: string, action: UsageType, inputType: InputType, prompt?: Prompt, inserted = false, sent = false) => { const chat = await ensureChat(); const timestamp = now(); const usage: Usage = { id: makeId('USE'), promptId: prompt?.id, promptVersion: prompt?.version, promptTitleSnapshot: prompt?.title, promptSnapshotHash: await hashText(text), chatId: chat?.id, chatName: chat?.localName, chatUrl: currentChat?.url, provider: currentChat?.provider, timestamp, usageType: action, inputType, variables: {}, wasModifiedBeforeUse: inputType === 'MODIFIED_PROMPT', inserted, sent, resultStatus: inserted || sent ? 'SUCCESS' : 'CANCELLED' }; const interaction: Interaction = { id: makeId('INT'), timestamp, chatId: chat?.id, provider: currentChat?.provider, url: currentChat?.url, promptId: prompt?.id, inputType, inputSnapshot: text, variables: {}, action, status: usage.resultStatus }; await UsageRepository.put(usage); await InteractionRepository.put(interaction); if (prompt) { await PromptRepository.put({ ...prompt, usageCount: prompt.usageCount + 1, lastUsedAt: timestamp }); } if (chat) await ChatRepository.put({ ...chat, promptUses: chat.promptUses + (prompt ? 1 : 0), interactions: chat.interactions + 1, lastUsedAt: timestamp }); await refresh(); };
  const insertOrSend = async (send: boolean) => { if (!composer.trim()) return notify('اكتب نصًا في Composer أولًا'); if (send && settings.confirmBeforeSend && !window.confirm('هل تريد إرسال النص إلى الدردشة الحالية؟')) return; try { const tabs = await chrome.tabs.query({ active: true, lastFocusedWindow: true }); const tab = tabs[0]; if (!tab?.id) throw new Error(); const inserted = await chrome.tabs.sendMessage(tab.id, { type: 'INSERT_TEXT', text: composer }); if (!inserted?.ok) throw new Error(); if (send) await chrome.tabs.sendMessage(tab.id, { type: 'SEND_MESSAGE' }); await record(composer, send ? 'INSERT_AND_SEND' : 'INSERT', selectedPrompt ? (composer === selectedPrompt.content ? 'STORED_PROMPT' : 'MODIFIED_PROMPT') : 'AD_HOC', selectedPrompt ?? undefined, true, send); notify(send ? 'تم الإدخال والإرسال وتسجيل العملية' : 'تم الإدخال وتسجيل العملية'); } catch { notify('تعذر العثور على مربع الإدخال في الصفحة الحالية'); } };
  const savePrompt = async (p: Prompt) => { if (!p.title.trim() || !p.content.trim()) return notify('العنوان والمحتوى مطلوبان'); const existing = prompts.find((x) => x.id === p.id); const saved = { ...p, updatedAt: now(), version: existing ? existing.version + (existing.content === p.content ? 0 : 1) : 1 }; await PromptRepository.put(saved); if (existing && existing.content !== p.content) await PromptVersionRepository.put({ id: makeId('VER'), promptId: p.id, version: saved.version, content: p.content, createdAt: now() }); setSelectedPrompt(null); setShowPromptForm(false); await refresh(); notify('تم حفظ البرومبت'); };
  const downloadBackup = async () => { const blob = new Blob([JSON.stringify(await exportBackup(), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `prompt-gateway-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); };
  const importFile = async (file?: File) => { if (!file) return; try { const result = await importBackup(JSON.parse(await file.text())); await refresh(); notify(`تم الاستيراد: ${result.imported} سجل، وتجاوز ${result.skipped}`); } catch { notify('ملف النسخة الاحتياطية غير صالح'); } };
  const usePrompt = (p: Prompt) => { setSelectedPrompt(p); setComposer(p.content); setView('home'); notify('تم تحميل البرومبت في Composer'); }; const syncCloud = async () => { if (!settings.googleClientId?.trim()) return notify('أدخل Google OAuth Client ID أولًا'); try { const result = await syncWithGoogle(settings.googleClientId); await refresh(); notify(result.message); } catch (error) { notify(error instanceof Error ? error.message : 'فشلت المزامنة مع Google Drive'); } };
  return <div className="app"><header><div><div className="eyebrow">LOCAL-FIRST WORKSPACE</div><h1>Prompt Gateway</h1></div><button className="icon-btn" onClick={detectCurrentChat} title="تحديث الدردشة الحالية">↻</button></header>
    <nav>{([['home','الرئيسية'],['prompts','البرومبتات'],['chats','الدردشات'],['activity','النشاط'],['settings','الإعدادات']] as [View,string][]).map(([id,label]) => <button key={id} className={view === id ? 'nav-active' : ''} onClick={() => { setView(id); setQuery(''); }}>{label}</button>)}</nav>
    {notice && <div className="notice">{notice}</div>}
    <main>{view === 'home' && <Home currentChat={currentChat} chats={chats} prompts={prompts} composer={composer} setComposer={setComposer} selectedPrompt={selectedPrompt} setSelectedPrompt={setSelectedPrompt} onInsert={() => insertOrSend(false)} onSend={() => insertOrSend(true)} onUse={usePrompt} onAddChat={async () => { await ensureChat(); await refresh(); notify('تم تسجيل الدردشة الحالية'); }} />}
      {view === 'prompts' && <section><Toolbar title="مستودع البرومبتات" query={query} setQuery={setQuery} action="إضافة Prompt" onAction={() => { setSelectedPrompt(emptyPrompt()); setShowPromptForm(true); }} /><div className="statline">{filteredPrompts.length} برومبت · {prompts.reduce((n, p) => n + p.usageCount, 0)} استخدام</div><div className="card-list">{filteredPrompts.map((p) => <PromptCard key={p.id} prompt={p} onUse={() => usePrompt(p)} onEdit={() => { setSelectedPrompt(p); setShowPromptForm(true); }} onDelete={async () => { if (window.confirm('حذف البرومبت من المستودع؟')) { await PromptRepository.remove(p.id); refresh(); } }} />)}{!filteredPrompts.length && <Empty text="لا توجد برومبتات بعد" />}</div></section>}
      {view === 'chats' && <section><Toolbar title="سجل الدردشات" query={query} setQuery={setQuery} action="إضافة دردشة" onAction={() => { setEditingChat(null); setShowChatForm(true); }} /><ChatFilters tags={chatTags} providers={chatProviders} selectedTag={chatTagFilter} setSelectedTag={setChatTagFilter} selectedProvider={chatProviderFilter} setSelectedProvider={setChatProviderFilter} favoritesOnly={chatFavoritesOnly} setFavoritesOnly={setChatFavoritesOnly} onReset={() => { setQuery(''); setChatTagFilter(''); setChatProviderFilter(''); setChatFavoritesOnly(false); }} resultCount={filteredChats.length} /><div className="card-list">{filteredChats.map((c) => <article className="card" key={c.id}><div className="card-head"><div><span className="provider">{c.provider}</span><h3>{c.localName}</h3><small>{c.originalTitle}</small></div><button onClick={() => chrome.tabs.create({ url: c.url })}>فتح</button></div><p className="url-line">{c.url}</p><p className="muted">{c.promptUses} استخدام Prompt · {c.interactions} تفاعل</p><div className="tags">{c.tags.map((t) => <span key={t}>{t}</span>)}</div><div className="card-foot"><span className="muted">{new Date(c.lastVisitedAt).toLocaleDateString('ar')}</span><div><button className="text-btn" onClick={async () => { if (window.confirm('حذف هذه الدردشة من السجل المحلي؟ لن تُحذف من الموقع الأصلي.')) { await ChatRepository.remove(c.id); refresh(); notify('تم حذف الدردشة من السجل'); } }}>حذف</button><button className="secondary" onClick={() => { setEditingChat(c); setShowChatForm(true); }}>تعديل</button></div></div></article>)}{!filteredChats.length && <Empty text="أضف دردشة يدويًا أو سجّل الدردشة الحالية" />}</div></section>}
      {view === 'activity' && <section><Toolbar title="سجل النشاط" query={query} setQuery={setQuery} /><div className="card-list">{[...usages].sort((a,b) => b.timestamp-a.timestamp).filter((u) => `${u.promptTitleSnapshot ?? 'Ad-hoc'} ${u.provider ?? ''} ${u.usageType}`.toLowerCase().includes(query.toLowerCase())).map((u) => <article className="activity-row" key={u.id}><div className="activity-dot" /><div><strong>{u.promptTitleSnapshot ?? 'Ad-hoc Input'}</strong><div className="muted">{u.provider ?? 'غير معروف'} · {u.usageType} · {new Date(u.timestamp).toLocaleString('ar')}</div><small>{u.chatName ?? 'دردشة غير مسجلة'}</small></div></article>)}{!usages.length && <Empty text="سيظهر سجل الاستخدام هنا" />}</div></section>}
      {view === 'settings' && <section><h2>الإعدادات</h2><div className="settings-card"><label className="switch-row"><span>تسجيل الدردشات تلقائيًا</span><input type="checkbox" checked={settings.autoRegisterChats} onChange={(e) => { const s = {...settings, autoRegisterChats: e.target.checked}; setSettings(s); SettingsRepository.put(s); }} /></label><label className="switch-row"><span>تأكيد قبل Insert & Send</span><input type="checkbox" checked={settings.confirmBeforeSend} onChange={(e) => { const s = {...settings, confirmBeforeSend: e.target.checked}; setSettings(s); SettingsRepository.put(s); }} /></label><label>Google OAuth Client ID<input dir="ltr" value={settings.googleClientId ?? ""} onChange={(e) => { const s = {...settings, googleClientId: e.target.value}; setSettings(s); SettingsRepository.put(s); }} placeholder="1234567890-....apps.googleusercontent.com" /></label><div className="sync-panel"><div><strong>مزامنة Google Drive</strong><small>{settings.lastSyncAt ? `آخر مزامنة: ${new Date(settings.lastSyncAt).toLocaleString("ar")}` : "لم تتم المزامنة بعد"}</small></div><button onClick={syncCloud}>Sync Now</button></div><label>المظهر<select value={settings.theme} onChange={(e) => { const s = {...settings, theme: e.target.value as Settings['theme']}; setSettings(s); SettingsRepository.put(s); }}><option value="system">النظام</option><option value="light">فاتح</option><option value="dark">داكن</option></select></label><div className="settings-actions"><button onClick={downloadBackup}>تصدير Full Backup</button><label className="button secondary">استيراد Backup<input hidden type="file" accept="application/json" onChange={(e) => importFile(e.target.files?.[0])} /></label></div></div><p className="muted">كل البيانات تبقى محليًا داخل IndexedDB. لا يوجد Backend أو Analytics في هذا الإصدار.</p></section>}
    </main>{showChatForm && <ChatForm chat={editingChat} currentChat={currentChat} onSave={async (chat) => { await ChatRepository.put(chat); setShowChatForm(false); setEditingChat(null); await refresh(); notify('تم حفظ الدردشة'); }} onCancel={() => { setShowChatForm(false); setEditingChat(null); }} />}{showPromptForm && selectedPrompt && <PromptForm prompt={selectedPrompt} onSave={savePrompt} onCancel={() => { setShowPromptForm(false); setSelectedPrompt(null); }} />}</div>;
}


function ChatFilters({ tags, providers, selectedTag, setSelectedTag, selectedProvider, setSelectedProvider, favoritesOnly, setFavoritesOnly, onReset, resultCount }: { tags: string[]; providers: string[]; selectedTag: string; setSelectedTag: (v: string) => void; selectedProvider: string; setSelectedProvider: (v: string) => void; favoritesOnly: boolean; setFavoritesOnly: (v: boolean) => void; onReset: () => void; resultCount: number }) { return <div className="advanced-filters"><div className="filter-row"><label>بحث شامل<input value={''} readOnly hidden /></label><select value={selectedTag} onChange={(e) => setSelectedTag(e.target.value)}><option value="">كل الوسوم</option>{tags.map((tag) => <option key={tag} value={tag}>Tag: {tag}</option>)}</select><select value={selectedProvider} onChange={(e) => setSelectedProvider(e.target.value)}><option value="">كل المواقع</option>{providers.map((provider) => <option key={provider} value={provider}>{provider}</option>)}</select><label className="filter-check"><input type="checkbox" checked={favoritesOnly} onChange={(e) => setFavoritesOnly(e.target.checked)} /> المفضلة فقط</label><button className="secondary" onClick={onReset}>إعادة ضبط</button></div><div className="filter-summary">{resultCount} دردشة مطابقة {selectedTag && <span>· الوسم: {selectedTag}</span>} {selectedProvider && <span>· الموقع: {selectedProvider}</span>}</div></div>; }
function Toolbar({ title, query, setQuery, action, onAction }: { title: string; query: string; setQuery: (v:string)=>void; action?: string; onAction?: ()=>void }) { return <div className="toolbar"><div><h2>{title}</h2><div className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث..." /></div></div>{action && <button onClick={onAction}>{action}</button>}</div>; }
function Home({ currentChat, chats, prompts, composer, setComposer, selectedPrompt, setSelectedPrompt, onInsert, onSend, onUse, onAddChat }: any) { const existing = chats.find((c: Chat) => c.identityKey === currentChat?.identityKey); return <section><div className="hero"><div><span className="eyebrow">CURRENT WORKSPACE</span><h2>مساحة العمل الموحدة</h2><p>اكتب من هنا، ثم أدخل المحتوى إلى الدردشة الحالية مع حفظ الأثر.</p></div><div className="hero-mark">PG</div></div><article className="current-chat card"><div className="card-head"><div><span className="provider">{currentChat?.provider ?? 'غير متصل'}</span><h3>{existing?.localName ?? currentChat?.title ?? 'لم يتم اكتشاف دردشة'}</h3><small>{currentChat?.url ?? 'افتح ChatGPT أو Claude في تبويب آخر'}</small></div>{currentChat && !existing && <button onClick={onAddChat}>إضافة الدردشة</button>}</div></article><div className="composer card"><div className="section-label">COMPOSER <span>{selectedPrompt ? `من: ${selectedPrompt.title}` : 'Ad-hoc Input'}</span></div><textarea value={composer} onChange={(e) => setComposer(e.target.value)} placeholder="اكتب النص أو اختر Prompt محفوظًا..." /><div className="composer-actions"><select defaultValue="" onChange={(e) => { const p = prompts.find((x: Prompt) => x.id === e.target.value); if (p) onUse(p); }}><option value="">اختيار Prompt...</option>{prompts.filter((p: Prompt) => !p.archived).map((p: Prompt) => <option key={p.id} value={p.id}>{p.title}</option>)}</select><button className="secondary" onClick={() => { setComposer(''); setSelectedPrompt(null); }}>مسح</button><button className="secondary" onClick={onInsert}>Insert</button><button onClick={onSend}>Insert & Send</button></div></div><div className="metrics"><Metric label="Prompts" value={prompts.length} /><Metric label="Chats" value={chats.length} /><Metric label="Uses" value={prompts.reduce((n: number,p:Prompt) => n+p.usageCount,0)} /></div></section>; }
function Metric({ label, value }: {label:string;value:number}) { return <div><strong>{value}</strong><span>{label}</span></div>; }
function PromptCard({ prompt, onUse, onEdit, onDelete }: any) { return <article className="card"><div className="card-head"><div><span className="provider">{prompt.category}</span><h3>{prompt.title}</h3><small>{prompt.description || 'بدون وصف'}</small></div><button className="star" onClick={async () => { await PromptRepository.put({...prompt, favorite: !prompt.favorite}); }}> {prompt.favorite ? '★' : '☆'} </button></div><p className="snippet">{prompt.content}</p><div className="card-foot"><span className="muted">{prompt.usageCount} استخدام · v{prompt.version}</span><div><button className="text-btn" onClick={onDelete}>حذف</button><button className="secondary" onClick={onEdit}>تعديل</button><button onClick={onUse}>Use</button></div></div></article>; }
function PromptForm({ prompt, onSave, onCancel }: {prompt:Prompt;onSave:(p:Prompt)=>void;onCancel:()=>void}) { const [p, setP] = useState(prompt); const set = (k: keyof Prompt, v: any) => setP({...p, [k]: v}); return <div className="modal-backdrop"><div className="modal"><div className="card-head"><h2>{prompt.title ? 'تعديل Prompt' : 'إضافة Prompt'}</h2><button className="icon-btn" onClick={onCancel}>×</button></div><label>العنوان<input value={p.title} onChange={(e)=>set('title',e.target.value)} /></label><label>الوصف<input value={p.description} onChange={(e)=>set('description',e.target.value)} /></label><label>المحتوى<textarea className="large" value={p.content} onChange={(e)=>set('content',e.target.value)} /></label><label>التصنيف<input value={p.category} onChange={(e)=>set('category',e.target.value)} /></label><label>Tags<input value={p.tags.join(', ')} onChange={(e)=>set('tags',e.target.value.split(',').map((x)=>x.trim()).filter(Boolean))} /></label><div className="modal-actions"><button className="secondary" onClick={onCancel}>إلغاء</button><button onClick={()=>onSave(p)}>حفظ</button></div></div></div>; }
function Empty({ text }: {text:string}) { return <div className="empty"><div>◌</div><p>{text}</p></div>; }

function ChatForm({ chat, currentChat, onSave, onCancel }: { chat: Chat | null; currentChat: CurrentChat | null; onSave: (chat: Chat) => void; onCancel: () => void }) { const base = chat ?? { id: makeId('CHT'), localName: currentChat?.title ?? '', originalTitle: currentChat?.title ?? '', url: currentChat?.url ?? '', provider: currentChat?.provider ?? 'generic', category: 'عام', tags: [], favorite: false, notes: '', createdAt: now(), firstSeenAt: now(), lastVisitedAt: now(), promptUses: 0, interactions: 0, archived: false, identityKey: currentChat?.identityKey ?? `manual:${crypto.randomUUID()}` }; const [c, setC] = useState<Chat>(base as Chat); const set = (k: keyof Chat, v: any) => setC({...c, [k]: v}); return <div className="modal-backdrop"><div className="modal"><div className="card-head"><h2>{chat ? 'تعديل الدردشة' : 'إضافة دردشة'}</h2><button className="icon-btn" onClick={onCancel}>×</button></div><label>الاسم المحلي<input value={c.localName} onChange={(e)=>set('localName',e.target.value)} placeholder="اسمك الخاص للدردشة" /></label><label>العنوان الأصلي<input value={c.originalTitle} onChange={(e)=>set('originalTitle',e.target.value)} /></label><label>الرابط الكامل للدردشة<input dir="ltr" value={c.url} onChange={(e)=>set('url',e.target.value)} placeholder="https://..." /></label><label>Provider / الموقع<input value={c.provider} onChange={(e)=>set('provider',e.target.value as any)} placeholder="chatgpt أو claude أو اسم الموقع" /></label><label>Tags<input value={c.tags.join(', ')} onChange={(e)=>set('tags',e.target.value.split(',').map((x)=>x.trim()).filter(Boolean))} /></label><label>ملاحظات<textarea value={c.notes} onChange={(e)=>set('notes',e.target.value)} /></label><div className="modal-actions"><button className="secondary" onClick={onCancel}>إلغاء</button><button onClick={()=>{ if (!c.localName.trim() || !c.url.trim()) return; onSave(c); }}>حفظ</button></div></div></div>; }
